---
- name: Install universal base packages
  pacman:
      name: "{{ base_packages }}"
      state: present
  tags:
    - packages

- name: Install AUR base packages
  become: true
  aur:
    name: "{{ aur.packages }}"
    user: "{{ user.name }}"
  tags:
    - aur
    - packages

