---
- name: Install sudo
  pacman: name=sudo state=present
  tags:
    - sudo

- name: Add user to wheel group
  user: name={{ user.name }} groups=wheel append=yes
  tags:
    - sudo
    - user

- name: Copy sudo configuration
  copy: 
    dest: /etc/sudoers.d/wheel.conf 
    mode: 440 
    content: |
      %wheel ALL=(ALL) ALL
  tags:
    - sudo
